- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: Install base tools
  block:
    - name: Install base tools on almalinux/9
      ansible.builtin.dnf:
        name:
        - glibc-langpack-ru
        - vim
        - traceroute
        - tcpdump
        - net-tools
        state: latest
        # disablerepo: appstream,baseos,extras
        # enablerepo: local
        # disable_gpg_check: true
        # update_cache: yes
        # install_weak_deps: false
      when: (ansible_os_family == "RedHat")

    - name: Install base tools on ubuntu/jammy64
      ansible.builtin.apt:
        name:
        - glibc-langpack-ru
        - vim
        - traceroute
        - tcpdump
        - net-tools
        state: latest
        # disablerepo: appstream,baseos,extras
        # enablerepo: local
        # disable_gpg_check: true
        # update_cache: yes
        # install_weak_deps: false
      when: (ansible_os_family == "Debian")
