- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: install base tools almalinux
  block:
    - name: update cache
      ansible.builtin.dnf:
        update_cache: yes

    - name: Install base tools
      ansible.builtin.dnf:
        name:
        - glibc-langpack-ru
        - vim
        - traceroute
        - tcpdump
        - net-tools
        state: latest
        # disablerepo: appstream,baseos,extras
        # enablerepo: local
        # disable_gpg_check: true
        # update_cache: yes
        # install_weak_deps: false
  when: (ansible_os_family == "RedHat")

- name: install base tools ubuntu
  block:
    - name: update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install base tools on ubuntu/jammy64
      ansible.builtin.apt:
        name:
        - language-pack-ru-base
        - vim
        - traceroute
        - tcpdump
        - net-tools
        state: latest
        # disablerepo: appstream,baseos,extras
        # enablerepo: local
        # disable_gpg_check: true
        # update_cache: yes
        # install_weak_deps: false
  when: (ansible_os_family == "Debian")
